services:
  postgis:
    image: postgis/postgis:17-master
    container_name: imprint-database
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pg_isready", "--host=localhost", "--username=directus"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s
    networks:
      - imprint-network
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: imprint-redis
    healthcheck:
      test: ["CMD-SHELL", "[ $$(redis-cli ping) = 'PONG' ]"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s
    env_file:
      - .env
    networks:
      - imprint-network
    restart: unless-stopped

  directus:
    image: directus/directus:latest
    container_name: imprint-directus
    ports:
      - 8050:8055
    volumes:
      - ./data/directus/uploads:/directus/uploads
      - ./data/directus/extensions:/directus/extensions
      - ./data/directus/templates:/directus/templates
    depends_on:
      postgis:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - imprint-network
    restart: unless-stopped

networks:
  imprint-network:
    name: imprint-network
    driver: bridge

